# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    cobra_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

cobra_arm_controller:
  ros__parameters:
    joints:
      - bottom_to_pedestal
      - pedestal_to_arm
      - arm_to_forearm
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints:
      - left_gripper_joint
      - right_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity