# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cobra_arm_controller
    - hand_controller

  cobra_arm_controller:
    type: FollowJointTrajectory
    joints:
      - bottom_to_pedestal
      - pedestal_to_arm
      - arm_to_forearm
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: FollowJointTrajectory
    joints:
      - left_gripper_joint
      - right_gripper_joint
    action_ns: follow_joint_trajectory
    default: true